// Comprehensive Global Stock, ETF, Derivative & Crypto Catalog
// Contains 250+ top worldwide instruments across US Big Tech, Cloud & Cybersecurity, Semiconductors,
// German DAX/MDAX/SDAX, European Blue Chips, US Finance, Pharma, Defense, Consumer, Auto, Energy, ETFs & Crypto.

(function () {
  const catalog = [
  // --- CLOUD, CYBERSECURITY, AI & SAAS ---
  { name: "Cloudflare Inc. (Class A)", ticker: "NET", assetType: "Aktie", sector: "Cloud & Cybersecurity", price: 272.95, dayChangePct: 2.59, isin: "US18915M1071" },
  { name: "CrowdStrike Holdings", ticker: "CRWD", assetType: "Aktie", sector: "Cybersecurity", price: 265.40, dayChangePct: 1.85, isin: "US22788C1053" },
  { name: "Palantir Technologies", ticker: "PLTR", assetType: "Aktie", sector: "Software & KI Analytics", price: 28.90, dayChangePct: 4.20, isin: "US69608A1088" },
  { name: "Snowflake Inc.", ticker: "SNOW", assetType: "Aktie", sector: "Cloud Data Platform", price: 118.20, dayChangePct: 0.95, isin: "US8334451098" },
  { name: "Datadog Inc.", ticker: "DDOG", assetType: "Aktie", sector: "Cloud Monitoring & Observability", price: 114.60, dayChangePct: 2.10, isin: "US23804L1035" },
  { name: "Palo Alto Networks", ticker: "PANW", assetType: "Aktie", sector: "Cybersecurity", price: 345.80, dayChangePct: 1.40, isin: "US6974351057" },
  { name: "Fortinet Inc.", ticker: "FTNT", assetType: "Aktie", sector: "Cybersecurity & Firewall", price: 74.20, dayChangePct: 0.85, isin: "US34959E1091" },
  { name: "Zscaler Inc.", ticker: "ZS", assetType: "Aktie", sector: "Cloud Security / Zero Trust", price: 182.50, dayChangePct: 1.90, isin: "US98980F1049" },
  { name: "SentinelOne Inc.", ticker: "S", assetType: "Aktie", sector: "Cybersecurity AI", price: 22.40, dayChangePct: 2.30, isin: "US81730H1095" },
  { name: "MongoDB Inc.", ticker: "MDB", assetType: "Aktie", sector: "Cloud Database", price: 278.30, dayChangePct: 1.65, isin: "US60855R1005" },
  { name: "Okta Inc.", ticker: "OKTA", assetType: "Aktie", sector: "Identity & Cloud Security", price: 78.40, dayChangePct: 0.70, isin: "US6792951054" },
  { name: "Shopify Inc.", ticker: "SHOP", assetType: "Aktie", sector: "E-Commerce Cloud", price: 76.50, dayChangePct: 2.80, isin: "CA82509L1076" },
  { name: "Atlassian Corporation", ticker: "TEAM", assetType: "Aktie", sector: "Software & Collaboration", price: 168.20, dayChangePct: 1.15, isin: "US0494681010" },
  { name: "ServiceNow Inc.", ticker: "NOW", assetType: "Aktie", sector: "Enterprise Cloud Software", price: 840.10, dayChangePct: 1.05, isin: "US81762P1021" },
  { name: "Salesforce Inc.", ticker: "CRM", assetType: "Aktie", sector: "Cloud CRM & Software", price: 254.80, dayChangePct: 0.45, isin: "US79466L3024" },
  { name: "Workday Inc.", ticker: "WDAY", assetType: "Aktie", sector: "HR & Enterprise Cloud", price: 242.00, dayChangePct: 0.80, isin: "US98138H1014" },
  { name: "HubSpot Inc.", ticker: "HUBS", assetType: "Aktie", sector: "Inbound Marketing Software", price: 512.30, dayChangePct: 1.35, isin: "US4435731009" },
  { name: "DocuSign Inc.", ticker: "DOCU", assetType: "Aktie", sector: "Digital Agreement Cloud", price: 58.60, dayChangePct: -0.40, isin: "US2561631068" },
  { name: "Zoom Video Communications", ticker: "ZM", assetType: "Aktie", sector: "Cloud Communications", price: 65.40, dayChangePct: 0.30, isin: "US98980L1017" },
  { name: "Twilio Inc.", ticker: "TWLO", assetType: "Aktie", sector: "Cloud Communications API", price: 62.10, dayChangePct: 1.70, isin: "US90138F1021" },
  { name: "Elastic N.V.", ticker: "ESTC", assetType: "Aktie", sector: "Search & Observability AI", price: 79.50, dayChangePct: 2.10, isin: "NL0013082699" },
  { name: "Dynatrace Inc.", ticker: "DT", assetType: "Aktie", sector: "Cloud Intelligence", price: 48.90, dayChangePct: 1.25, isin: "US2681501092" },
  { name: "UiPath Inc.", ticker: "PATH", assetType: "Aktie", sector: "RPA & Automation AI", price: 12.80, dayChangePct: 1.95, isin: "US90364P1057" },

  // --- US BIG TECH & MEGA-CAPS ---
  { name: "NVIDIA Corporation", ticker: "NVDA", assetType: "Aktie", sector: "Halbleiter / KI Hardware", price: 128.40, dayChangePct: 3.15, isin: "US67066G1040" },
  { name: "Apple Inc.", ticker: "AAPL", assetType: "Aktie", sector: "Consumer Electronics & Services", price: 224.30, dayChangePct: 0.85, isin: "US0378331005" },
  { name: "Microsoft Corporation", ticker: "MSFT", assetType: "Aktie", sector: "Software & Cloud / KI", price: 448.20, dayChangePct: -0.42, isin: "US5949181045" },
  { name: "Amazon.com Inc.", ticker: "AMZN", assetType: "Aktie", sector: "E-Commerce & AWS Cloud", price: 186.50, dayChangePct: 1.12, isin: "US0231351067" },
  { name: "Alphabet Inc. (Google A)", ticker: "GOOGL", assetType: "Aktie", sector: "Internet, Search & Cloud", price: 178.90, dayChangePct: 0.64, isin: "US02079K3059" },
  { name: "Meta Platforms Inc.", ticker: "META", assetType: "Aktie", sector: "Social Media, KI & VR", price: 512.40, dayChangePct: 2.45, isin: "US30303M1027" },
  { name: "Tesla Inc.", ticker: "TSLA", assetType: "Aktie", sector: "Automobil / EV & Energy", price: 286.55, dayChangePct: 1.89, isin: "US88160R1014" },
  { name: "Netflix Inc.", ticker: "NFLX", assetType: "Aktie", sector: "Entertainment & Streaming", price: 685.10, dayChangePct: 1.30, isin: "US64110L1061" },
  { name: "Broadcom Inc.", ticker: "AVGO", assetType: "Aktie", sector: "Halbleiter & Enterprise Infra", price: 162.80, dayChangePct: 2.30, isin: "US11135F1012" },
  { name: "Adobe Inc.", ticker: "ADBE", assetType: "Aktie", sector: "Kreativ- & Cloud-Software", price: 535.40, dayChangePct: 0.90, isin: "US00724F1012" },
  { name: "Oracle Corporation", ticker: "ORCL", assetType: "Aktie", sector: "Cloud Infrastructure & Database", price: 142.60, dayChangePct: 1.75, isin: "US68389X1054" },
  { name: "Cisco Systems", ticker: "CSCO", assetType: "Aktie", sector: "Netzwerk & Cybersecurity", price: 49.80, dayChangePct: 0.20, isin: "US17275R1023" },
  { name: "IBM (International Business Machines)", ticker: "IBM", assetType: "Aktie", sector: "IT-Services & Hybrid Cloud", price: 194.20, dayChangePct: 0.60, isin: "US4592001014" },
  { name: "Intuit Inc.", ticker: "INTU", assetType: "Aktie", sector: "Finanzsoftware & TurboTax", price: 645.00, dayChangePct: 0.70, isin: "US4612021034" },
  { name: "Super Micro Computer", ticker: "SMCI", assetType: "Aktie", sector: "Server & KI-Hardware", price: 42.50, dayChangePct: -1.20, isin: "US86800U1043" },
  { name: "MicroStrategy Inc.", ticker: "MSTR", assetType: "Aktie", sector: "Enterprise Software & Bitcoin", price: 135.20, dayChangePct: 7.40, isin: "US5949724083" },
  { name: "Dell Technologies", ticker: "DELL", assetType: "Aktie", sector: "Server, PC & KI-Infrastruktur", price: 112.40, dayChangePct: 1.80, isin: "US24703L2025" },

  // --- HALBLEITER & CHIP-EQUIPMENT ---
  { name: "Taiwan Semiconductor (TSMC)", ticker: "TSM", assetType: "Aktie", sector: "Halbleiter-Foundry", price: 165.20, dayChangePct: 2.90, isin: "US8740391004" },
  { name: "ASML Holding NV", ticker: "ASML", assetType: "Aktie", sector: "Halbleiter-Lithografie (EUV)", price: 812.00, dayChangePct: 1.45, isin: "NL0010273215" },
  { name: "Advanced Micro Devices (AMD)", ticker: "AMD", assetType: "Aktie", sector: "CPUs & KI-GPUs", price: 156.80, dayChangePct: 1.95, isin: "US0079031078" },
  { name: "Qualcomm Inc.", ticker: "QCOM", assetType: "Aktie", sector: "Mobile Prozessoren & 5G", price: 168.40, dayChangePct: 1.10, isin: "US7475251036" },
  { name: "Intel Corporation", ticker: "INTC", assetType: "Aktie", sector: "Halbleiter & Foundry", price: 21.40, dayChangePct: -1.15, isin: "US4581401001" },
  { name: "Applied Materials", ticker: "AMAT", assetType: "Aktie", sector: "Halbleiter-Equipment", price: 198.50, dayChangePct: 1.60, isin: "US0382221051" },
  { name: "Lam Research", ticker: "LRCX", assetType: "Aktie", sector: "Halbleiter-Ausrüstung", price: 785.00, dayChangePct: 1.70, isin: "US5128071082" },
  { name: "KLA Corporation", ticker: "KLAC", assetType: "Aktie", sector: "Halbleiter-Prozesskontrolle", price: 692.00, dayChangePct: 1.50, isin: "US4824801009" },
  { name: "Micron Technology", ticker: "MU", assetType: "Aktie", sector: "Speicherchips (DRAM/NAND)", price: 92.40, dayChangePct: 2.40, isin: "US5951121038" },
  { name: "ARM Holdings plc", ticker: "ARM", assetType: "Aktie", sector: "Chip-Architektur & IP", price: 128.50, dayChangePct: 3.80, isin: "US0420681068" },
  { name: "Marvell Technology", ticker: "MRVL", assetType: "Aktie", sector: "Netzwerk- & Datacenter-Chips", price: 72.80, dayChangePct: 2.15, isin: "US5738741041" },
  { name: "Texas Instruments", ticker: "TXN", assetType: "Aktie", sector: "Analogchips & Embedded", price: 192.30, dayChangePct: 0.35, isin: "US8825081040" },
  { name: "Synopsys Inc.", ticker: "SNPS", assetType: "Aktie", sector: "EDA Chipdesign-Software", price: 540.20, dayChangePct: 1.10, isin: "US8716071076" },
  { name: "Cadence Design Systems", ticker: "CDNS", assetType: "Aktie", sector: "EDA & Halbleitersoftware", price: 285.40, dayChangePct: 0.95, isin: "US1273871087" },
  { name: "Infineon Technologies AG", ticker: "IFX", assetType: "Aktie", sector: "Power- & Automotive-Chips", price: 31.80, dayChangePct: 1.15, isin: "DE0006231004" },
  { name: "STMicroelectronics N.V.", ticker: "STMPA", assetType: "Aktie", sector: "Halbleiter", price: 27.40, dayChangePct: 0.60, isin: "NL0000226223" },
  { name: "Aixtron SE", ticker: "AIXA", assetType: "Aktie", sector: "Halbleiter-Depositionsanlagen", price: 15.60, dayChangePct: 2.10, isin: "DE000A0WMPJ6" },

  // --- DEUTSCHE AKTIEN (DAX 40, MDAX & SDAX) ---
  { name: "SAP SE", ticker: "SAP", assetType: "Aktie", sector: "Unternehmenssoftware & Cloud", price: 198.60, dayChangePct: 0.75, isin: "DE0007164600" },
  { name: "Siemens AG", ticker: "SIE", assetType: "Aktie", sector: "Industrie, Automatisierung & Digitalisierung", price: 172.10, dayChangePct: 0.55, isin: "DE0007236101" },
  { name: "Allianz SE", ticker: "ALV", assetType: "Aktie", sector: "Versicherung & Asset Management", price: 268.40, dayChangePct: 0.30, isin: "DE0008404005" },
  { name: "Deutsche Telekom AG", ticker: "DTE", assetType: "Aktie", sector: "Telekommunikation & 5G", price: 24.80, dayChangePct: 0.40, isin: "DE0005557508" },
  { name: "Mercedes-Benz Group AG", ticker: "MBG", assetType: "Aktie", sector: "Automobil / Premium", price: 62.40, dayChangePct: -0.30, isin: "DE0007100000" },
  { name: "BMW AG (Bayerische Motoren Werke)", ticker: "BMW", assetType: "Aktie", sector: "Automobil / Premium", price: 84.60, dayChangePct: 0.12, isin: "DE0005190003" },
  { name: "Volkswagen AG Vz.", ticker: "VOW3", assetType: "Aktie", sector: "Automobilkonzern", price: 98.20, dayChangePct: -0.65, isin: "DE0007664039" },
  { name: "Porsche AG Vz.", ticker: "P911", assetType: "Aktie", sector: "Sportwagen / Luxus-Automobil", price: 71.50, dayChangePct: 0.10, isin: "DE000PAG9113" },
  { name: "Porsche Automobil Holding SE", ticker: "PAH3", assetType: "Aktie", sector: "Holding / Automobilbeteiligungen", price: 42.10, dayChangePct: -0.20, isin: "DE000PAH0038" },
  { name: "Rheinmetall AG", ticker: "RHM", assetType: "Aktie", sector: "Verteidigung & Rüstungstechnologie", price: 492.00, dayChangePct: 2.80, isin: "DE0007030009" },
  { name: "Münchener Rück (Munich Re)", ticker: "MUV2", assetType: "Aktie", sector: "Rückversicherung", price: 462.80, dayChangePct: 0.65, isin: "DE0008430026" },
  { name: "Deutsche Bank AG", ticker: "DBK", assetType: "Aktie", sector: "Banken & Investment", price: 14.85, dayChangePct: 1.10, isin: "DE0005140008" },
  { name: "Commerzbank AG", ticker: "CBK", assetType: "Aktie", sector: "Banken & Mittelstand", price: 14.20, dayChangePct: 1.35, isin: "DE000CBK1001" },
  { name: "BASF SE", ticker: "BAS", assetType: "Aktie", sector: "Chemiekonzern", price: 44.50, dayChangePct: -0.15, isin: "DE000BASF111" },
  { name: "Bayer AG", ticker: "BAYN", assetType: "Aktie", sector: "Pharma & Agrarchemie", price: 27.30, dayChangePct: 0.40, isin: "DE000BAY0017" },
  { name: "DHL Group (Deutsche Post)", ticker: "DHL", assetType: "Aktie", sector: "Logistik & Expressversand", price: 38.60, dayChangePct: -0.25, isin: "DE0005552004" },
  { name: "Continental AG", ticker: "CON", assetType: "Aktie", sector: "Automobilzulieferer & Reifen", price: 56.40, dayChangePct: -0.80, isin: "DE0005439004" },
  { name: "Heidelberg Materials AG", ticker: "HEI", assetType: "Aktie", sector: "Baustoffe & Zement", price: 98.60, dayChangePct: 0.90, isin: "DE0006047004" },
  { name: "E.ON SE", ticker: "EOAN", assetType: "Aktie", sector: "Energienetze & Infrastruktur", price: 12.80, dayChangePct: 0.20, isin: "DE000ENAG999" },
  { name: "RWE AG", ticker: "RWE", assetType: "Aktie", sector: "Erneuerbare Energien & Strom", price: 32.40, dayChangePct: 0.45, isin: "DE0007037129" },
  { name: "Beiersdorf AG", ticker: "BEI", assetType: "Aktie", sector: "Konsumgüter & Hautpflege (Nivea)", price: 138.20, dayChangePct: 0.15, isin: "DE0005200000" },
  { name: "Henkel AG & Co. KGaA Vz.", ticker: "HEN3", assetType: "Aktie", sector: "Konsumgüter & Klebstoffe", price: 82.50, dayChangePct: 0.35, isin: "DE0006048432" },
  { name: "Symrise AG", ticker: "SY1", assetType: "Aktie", sector: "Duft- & Geschmacksstoffe", price: 114.00, dayChangePct: 0.50, isin: "DE000SYM9999" },
  { name: "Sartorius AG Vz.", ticker: "SRT3", assetType: "Aktie", sector: "Biopharma-Ausrüstung", price: 236.40, dayChangePct: 1.80, isin: "DE0007165631" },
  { name: "QIAGEN N.V.", ticker: "QIA", assetType: "Aktie", sector: "Molekulare Diagnostik", price: 40.20, dayChangePct: 0.10, isin: "NL0012169213" },
  { name: "Siemens Healthineers AG", ticker: "SHL", assetType: "Aktie", sector: "Medizintechnik & Bildgebung", price: 52.60, dayChangePct: 0.70, isin: "DE000SHL1006" },
  { name: "Siemens Energy AG", ticker: "ENR", assetType: "Aktie", sector: "Energietechnik & Netze", price: 24.50, dayChangePct: 3.40, isin: "DE000ENER6Y0" },
  { name: "Fresenius SE & Co. KGaA", ticker: "FRE", assetType: "Aktie", sector: "Gesundheitskonzern & Kliniken", price: 31.20, dayChangePct: 0.60, isin: "DE0005785604" },
  { name: "Fresenius Medical Care", ticker: "FME", assetType: "Aktie", sector: "Dialyse & Nierentherapie", price: 38.90, dayChangePct: 0.25, isin: "DE0005785802" },
  { name: "Vonovia SE", ticker: "VNA", assetType: "Aktie", sector: "Immobilien", price: 28.60, dayChangePct: 1.10, isin: "DE000A1ML7J1" },
  { name: "MTU Aero Engines AG", ticker: "MTX", assetType: "Aktie", sector: "Luftfahrt & Triebwerke", price: 265.00, dayChangePct: 1.05, isin: "DE000A0D9PT0" },
  { name: "Hannover Rück SE", ticker: "HNR1", assetType: "Aktie", sector: "Rückversicherung", price: 242.00, dayChangePct: 0.40, isin: "DE0008402215" },
  { name: "Brenntag SE", ticker: "BNR", assetType: "Aktie", sector: "Chemiedistribution", price: 68.20, dayChangePct: -0.10, isin: "DE000A1DAHH0" },
  { name: "Adidas AG", ticker: "ADS", assetType: "Aktie", sector: "Sportbekleidung & Schuhe", price: 218.40, dayChangePct: 1.30, isin: "DE000A1EWWW0" },
  { name: "Puma SE", ticker: "PUM", assetType: "Aktie", sector: "Sportartikel", price: 36.80, dayChangePct: -0.50, isin: "DE0006969603" },
  { name: "Zalando SE", ticker: "ZAL", assetType: "Aktie", sector: "Online-Modehandel", price: 24.10, dayChangePct: 1.85, isin: "DE000ZAL1111" },
  { name: "HelloFresh SE", ticker: "HFG", assetType: "Aktie", sector: "Kochboxen & E-Commerce", price: 6.80, dayChangePct: -2.10, isin: "DE000A161408" },
  { name: "Delivery Hero SE", ticker: "DHER", assetType: "Aktie", sector: "Essenslieferdienst", price: 22.90, dayChangePct: 2.20, isin: "DE000A2E4K43" },
  { name: "Scout24 SE", ticker: "G24", assetType: "Aktie", sector: "Immobilienplattform (ImmoScout)", price: 74.50, dayChangePct: 0.40, isin: "DE000A12DM80" },
  { name: "Nemetschek SE", ticker: "NEM", assetType: "Aktie", sector: "Bausoftware & CAD", price: 92.30, dayChangePct: 0.85, isin: "DE0006452907" },
  { name: "CTS Eventim AG & Co. KGaA", ticker: "EVD", assetType: "Aktie", sector: "Ticketing & Live Entertainment", price: 82.10, dayChangePct: 1.00, isin: "DE0005470306" },
  { name: "Hensoldt AG", ticker: "HAGG", assetType: "Aktie", sector: "Verteidigungselektronik & Radar", price: 34.20, dayChangePct: 2.40, isin: "DE000HENS999" },
  { name: "Renk Group AG", ticker: "R3NK", assetType: "Aktie", sector: "Panzergetriebe & Verteidigung", price: 23.80, dayChangePct: 3.10, isin: "DE000RENK730" },
  { name: "Carl Zeiss Meditec AG", ticker: "AFX", assetType: "Aktie", sector: "Medizintechnik & Optik", price: 64.50, dayChangePct: -0.70, isin: "DE0005313704" },
  { name: "Nordex SE", ticker: "NDX1", assetType: "Aktie", sector: "Windkraftanlagen", price: 13.90, dayChangePct: 1.70, isin: "DE000A0D6554" },
  { name: "SMA Solar Technology AG", ticker: "S92", assetType: "Aktie", sector: "Solarwechselrichter", price: 19.40, dayChangePct: -1.80, isin: "DE000A0DJ6J9" },
  { name: "Evotec SE", ticker: "EVT", assetType: "Aktie", sector: "Wirkstoffforschung & Biotech", price: 5.60, dayChangePct: 3.20, isin: "DE0005664809" },
  { name: "Knorr-Bremse AG", ticker: "KBX", assetType: "Aktie", sector: "Bremssysteme Schiene & LKW", price: 73.10, dayChangePct: 0.50, isin: "DE000KBX1006" },
  { name: "Thyssenkrupp AG", ticker: "TKA", assetType: "Aktie", sector: "Industriekonzern & Stahl", price: 3.40, dayChangePct: -0.90, isin: "DE0007500001" },
  { name: "TUI AG", ticker: "TUI1", assetType: "Aktie", sector: "Touristik & Reisekonzern", price: 6.75, dayChangePct: 1.10, isin: "DE000TUAG505" },
  { name: "Bechtle AG", ticker: "BC8", assetType: "Aktie", sector: "IT-Systemhaus & E-Commerce", price: 42.80, dayChangePct: 0.30, isin: "DE0005158703" },
  { name: "TeamViewer SE", ticker: "TMV", assetType: "Aktie", sector: "Fernwartungssoftware", price: 12.30, dayChangePct: 0.80, isin: "DE000A2YN900" },
  { name: "BioNTech SE", ticker: "BNTX", assetType: "Aktie", sector: "Biopharma & mRNA Krebsforschung", price: 82.40, dayChangePct: -0.50, isin: "US09075V1026" },

  // --- EUROPÄISCHE MEGAMÄRKTE & WELTMARKTFÜHRER ---
  { name: "Novo Nordisk A/S (Class B)", ticker: "NOVO B", assetType: "Aktie", sector: "Pharma / Diabetes & Adipositas (Ozempic/Wegovy)", price: 124.60, dayChangePct: -0.80, isin: "DK0062498333" },
  { name: "LVMH Moët Hennessy Louis Vuitton", ticker: "MC", assetType: "Aktie", sector: "Luxusgüter & Mode", price: 685.00, dayChangePct: 0.80, isin: "FR0000121014" },
  { name: "Hermès International", ticker: "RMS", assetType: "Aktie", sector: "Ultra-Luxusgüter & Leder", price: 2140.00, dayChangePct: 1.10, isin: "FR0000052292" },
  { name: "L'Oréal S.A.", ticker: "OR", assetType: "Aktie", sector: "Kosmetik & Schönheitspflege", price: 382.50, dayChangePct: 0.40, isin: "FR0000120321" },
  { name: "Ferrari N.V.", ticker: "RACE", assetType: "Aktie", sector: "Luxus-Sportwagen", price: 412.00, dayChangePct: 1.20, isin: "NL0011585146" },
  { name: "Nestlé S.A.", ticker: "NESN", assetType: "Aktie", sector: "Lebensmittel & Konsumgüter", price: 88.40, dayChangePct: -0.20, isin: "CH0038863350" },
  { name: "Roche Holding AG", ticker: "ROG", assetType: "Aktie", sector: "Pharma & Diagnostik", price: 274.00, dayChangePct: 0.35, isin: "CH0012032048" },
  { name: "Novartis AG", ticker: "NOVN", assetType: "Aktie", sector: "Pharma & Innovative Medikamente", price: 98.20, dayChangePct: 0.50, isin: "CH0012005267" },
  { name: "Sanofi S.A.", ticker: "SAN", assetType: "Aktie", sector: "Pharma & Impfstoffe", price: 102.40, dayChangePct: 0.60, isin: "FR0000120578" },
  { name: "AstraZeneca PLC", ticker: "AZN", assetType: "Aktie", sector: "Pharma & Onkologie", price: 148.50, dayChangePct: 0.85, isin: "GB0009895292" },
  { name: "TotalEnergies SE", ticker: "TTE", assetType: "Aktie", sector: "Energie, Öl & Gas / Renewables", price: 62.80, dayChangePct: 0.90, isin: "FR0000120271" },
  { name: "Shell PLC", ticker: "SHEL", assetType: "Aktie", sector: "Energie, LNG & Erdöl", price: 31.50, dayChangePct: 0.70, isin: "GB00BP6MXD84" },
  { name: "BP p.l.c.", ticker: "BP", assetType: "Aktie", sector: "Energie & Raffinerie", price: 4.80, dayChangePct: 0.40, isin: "GB0007980591" },
  { name: "Schneider Electric SE", ticker: "SU", assetType: "Aktie", sector: "Energiemanagement & Automation", price: 228.00, dayChangePct: 1.30, isin: "FR0000121972" },
  { name: "Air Liquide S.A.", ticker: "AI", assetType: "Aktie", sector: "Industriegase & Wasserstoff", price: 172.50, dayChangePct: 0.45, isin: "FR0000120073" },
  { name: "Airbus SE", ticker: "AIR", assetType: "Aktie", sector: "Luft- & Raumfahrt / Verkehrsflugzeuge", price: 138.40, dayChangePct: 0.80, isin: "NL0000235190" },
  { name: "Iberdrola S.A.", ticker: "IBE", assetType: "Aktie", sector: "Erneuerbare Energien & Strom", price: 12.60, dayChangePct: 0.30, isin: "ES0144580Y14" },
  { name: "Enel S.p.A.", ticker: "ENEL", assetType: "Aktie", sector: "Energieversorgung", price: 6.80, dayChangePct: 0.15, isin: "IT0003128367" },
  { name: "Banco Santander S.A.", ticker: "SAN", assetType: "Aktie", sector: "Banken & Finanzdienstleistungen", price: 4.40, dayChangePct: 1.20, isin: "ES0113900J37" },
  { name: "BNP Paribas S.A.", ticker: "BNP", assetType: "Aktie", sector: "Europäische Großbank", price: 61.80, dayChangePct: 0.95, isin: "FR0000131104" },
  { name: "Intesa Sanpaolo S.p.A.", ticker: "ISP", assetType: "Aktie", sector: "Banken", price: 3.75, dayChangePct: 0.80, isin: "IT0000072618" },
  { name: "UBS Group AG", ticker: "UBSG", assetType: "Aktie", sector: "Vermögensverwaltung & Banking", price: 28.90, dayChangePct: 1.05, isin: "CH0244767585" },
  { name: "Stellantis N.V.", ticker: "STLAM", assetType: "Aktie", sector: "Automobil (Peugeot/Fiat/Jeep)", price: 14.50, dayChangePct: -1.10, isin: "NL00150001Q9" },
  { name: "Inditex S.A. (Zara)", ticker: "ITX", assetType: "Aktie", sector: "Modekonzern & Fast Fashion", price: 46.20, dayChangePct: 0.70, isin: "ES0148396007" },
  { name: "Heineken N.V.", ticker: "HEIA", assetType: "Aktie", sector: "Brauerei & Getränke", price: 78.40, dayChangePct: 0.10, isin: "NL0000009165" },
  { name: "Anheuser-Busch InBev", ticker: "ABI", assetType: "Aktie", sector: "Getränke & Brauereikonzern", price: 56.20, dayChangePct: 0.30, isin: "BE0974293251" },
  { name: "Volvo Group (AB Volvo B)", ticker: "VOLV B", assetType: "Aktie", sector: "Nutzfahrzeuge & LKW", price: 24.80, dayChangePct: 0.50, isin: "SE0000115446" },
  { name: "Adyen N.V.", ticker: "ADYEN", assetType: "Aktie", sector: "Globales Payment & Fintech", price: 1320.00, dayChangePct: 2.30, isin: "NL0012969182" },
  { name: "Prosus N.V.", ticker: "PRX", assetType: "Aktie", sector: "Tech-Beteiligungen & Tencent", price: 34.50, dayChangePct: 1.40, isin: "NL0013654783" },
  { name: "Safran S.A.", ticker: "SAF", assetType: "Aktie", sector: "Luftfahrt & Triebwerkbau", price: 198.00, dayChangePct: 0.90, isin: "FR0000073272" },
  { name: "Kering S.A. (Gucci)", ticker: "KER", assetType: "Aktie", sector: "Luxusgüter & Mode", price: 235.00, dayChangePct: -0.80, isin: "FR0000121485" },
  { name: "Rio Tinto PLC", ticker: "RIO", assetType: "Aktie", sector: "Bergbau, Eisenerz & Metalle", price: 58.40, dayChangePct: 0.60, isin: "GB0007188757" },
  { name: "Glencore PLC", ticker: "GLEN", assetType: "Aktie", sector: "Rohstoffhandel & Bergbau", price: 4.60, dayChangePct: 0.30, isin: "JE00B4T3BW64" },

  // --- US BANKEN, FINANZEN & FINTECH ---
  { name: "Berkshire Hathaway Inc. (Class B)", ticker: "BRK.B", assetType: "Aktie", sector: "Mischkonzern / Warren Buffett", price: 445.50, dayChangePct: 0.35, isin: "US0846707026" },
  { name: "JPMorgan Chase & Co.", ticker: "JPM", assetType: "Aktie", sector: "Großbank & Investment Banking", price: 218.40, dayChangePct: 0.90, isin: "US46625H1005" },
  { name: "Visa Inc. (Class A)", ticker: "V", assetType: "Aktie", sector: "Zahlungsnetzwerk & Payments", price: 278.50, dayChangePct: 0.40, isin: "US92826C8394" },
  { name: "Mastercard Inc.", ticker: "MA", assetType: "Aktie", sector: "Zahlungsdienstleister & FinTech", price: 485.00, dayChangePct: 0.45, isin: "US57636Q1040" },
  { name: "Bank of America Corp.", ticker: "BAC", assetType: "Aktie", sector: "Großbank & Retail Banking", price: 39.80, dayChangePct: 0.75, isin: "US0605051046" },
  { name: "Wells Fargo & Co.", ticker: "WFC", assetType: "Aktie", sector: "US-Großbank", price: 54.60, dayChangePct: 0.60, isin: "US9497461015" },
  { name: "Goldman Sachs Group", ticker: "GS", assetType: "Aktie", sector: "Investment Banking & Trading", price: 485.20, dayChangePct: 1.15, isin: "US38141G1040" },
  { name: "Morgan Stanley", ticker: "MS", assetType: "Aktie", sector: "Wealth Management & Banking", price: 98.40, dayChangePct: 0.85, isin: "US6174464486" },
  { name: "BlackRock Inc.", ticker: "BLK", assetType: "Aktie", sector: "Weltgrößter Asset Manager (iShares)", price: 865.00, dayChangePct: 0.70, isin: "US09247X1019" },
  { name: "American Express Co.", ticker: "AXP", assetType: "Aktie", sector: "Kreditkarten & Premium-Finance", price: 248.60, dayChangePct: 0.90, isin: "US0258161092" },
  { name: "Citigroup Inc.", ticker: "C", assetType: "Aktie", sector: "Globales Bankgeschäft", price: 58.20, dayChangePct: 0.50, isin: "US1729674242" },
  { name: "S&P Global Inc.", ticker: "SPGI", assetType: "Aktie", sector: "Finanzdaten, Ratings & Indizes", price: 512.00, dayChangePct: 0.65, isin: "US78409V1044" },
  { name: "Moody's Corporation", ticker: "MCO", assetType: "Aktie", sector: "Kreditratings & Finanzanalysen", price: 462.00, dayChangePct: 0.55, isin: "US6153691059" },
  { name: "PayPal Holdings", ticker: "PYPL", assetType: "Aktie", sector: "Digitales Payment", price: 68.40, dayChangePct: 1.45, isin: "US70450Y1038" },
  { name: "Block Inc. (Square / Cash App)", ticker: "SQ", assetType: "Aktie", sector: "Fintech & Mobile Payments", price: 58.40, dayChangePct: 2.10, isin: "US8522341036" },
  { name: "Robinhood Markets", ticker: "HOOD", assetType: "Aktie", sector: "Fintech Brokerage & Krypto", price: 19.80, dayChangePct: 4.50, isin: "US7707001027" },
  { name: "Coinbase Global Inc.", ticker: "COIN", assetType: "Aktie", sector: "Kryptobörse & Web3-Infrastruktur", price: 215.30, dayChangePct: 6.80, isin: "US19260Q1076" },
  { name: "Interactive Brokers Group", ticker: "IBKR", assetType: "Aktie", sector: "Globaler Online-Broker", price: 124.50, dayChangePct: 1.20, isin: "US45841N1072" },
  { name: "Charles Schwab Corp.", ticker: "SCHW", assetType: "Aktie", sector: "Brokerage & Banking", price: 64.80, dayChangePct: 0.40, isin: "US8085131055" },

  // --- PHARMA, HEALTHCARE & BIOTECH ---
  { name: "Eli Lilly and Company", ticker: "LLY", assetType: "Aktie", sector: "Pharma / Adipositas & Diabetes (Mounjaro/Zepbound)", price: 845.20, dayChangePct: 1.15, isin: "US5324571083" },
  { name: "Johnson & Johnson", ticker: "JNJ", assetType: "Aktie", sector: "Pharma & Medizintechnik", price: 162.40, dayChangePct: 0.10, isin: "US4781601046" },
  { name: "UnitedHealth Group", ticker: "UNH", assetType: "Aktie", sector: "Krankenversicherung & HealthTech", price: 574.00, dayChangePct: 0.35, isin: "US91324P1021" },
  { name: "Pfizer Inc.", ticker: "PFE", assetType: "Aktie", sector: "Pharma & Impfstoffe", price: 28.50, dayChangePct: -0.20, isin: "US7170811035" },
  { name: "AbbVie Inc.", ticker: "ABBV", assetType: "Aktie", sector: "Biopharma & Immunologie (Humira/Skyrizi)", price: 194.20, dayChangePct: 0.50, isin: "US00287Y1091" },
  { name: "Merck & Co. Inc.", ticker: "MRK", assetType: "Aktie", sector: "Pharma & Krebsimmuntherapie (Keytruda)", price: 116.80, dayChangePct: 0.25, isin: "US58933Y1055" },
  { name: "Thermo Fisher Scientific", ticker: "TMO", assetType: "Aktie", sector: "Laborausrüstung & Biotech-Services", price: 582.00, dayChangePct: 0.60, isin: "US8835561023" },
  { name: "Abbott Laboratories", ticker: "ABT", assetType: "Aktie", sector: "Diagnostik & Medizintechnik", price: 112.40, dayChangePct: 0.40, isin: "US0028241000" },
  { name: "Danaher Corporation", ticker: "DHR", assetType: "Aktie", sector: "Life Sciences & Medizintechnik", price: 268.00, dayChangePct: 0.70, isin: "US2358511028" },
  { name: "Amgen Inc.", ticker: "AMGN", assetType: "Aktie", sector: "Biopharmazeutika", price: 324.50, dayChangePct: 0.80, isin: "US0311621009" },
  { name: "Gilead Sciences", ticker: "GILD", assetType: "Aktie", sector: "Virologie & Onkologie", price: 81.20, dayChangePct: 0.45, isin: "US3755581036" },
  { name: "Moderna Inc.", ticker: "MRNA", assetType: "Aktie", sector: "mRNA Impfstoffe & Therapien", price: 68.40, dayChangePct: -1.20, isin: "US60770K1079" },
  { name: "Vertex Pharmaceuticals", ticker: "VRTX", assetType: "Aktie", sector: "Mukoviszidose & Gentherapie", price: 478.00, dayChangePct: 0.90, isin: "US92532F1003" },
  { name: "Intuitive Surgical", ticker: "ISRG", assetType: "Aktie", sector: "Operationsroboter (da Vinci)", price: 468.00, dayChangePct: 1.40, isin: "US46120E6023" },
  { name: "Stryker Corporation", ticker: "SYK", assetType: "Aktie", sector: "Orthopädie & Medizintechnik", price: 358.00, dayChangePct: 0.55, isin: "US8636671013" },
  { name: "CRISPR Therapeutics AG", ticker: "CRSP", assetType: "Aktie", sector: "Gen-Editing (CRISPR/Cas9)", price: 48.60, dayChangePct: 2.10, isin: "CH0334081137" },

  // --- KONSUM, HANDEL, MEDIEN & MOBILITÄT ---
  { name: "Walmart Inc.", ticker: "WMT", assetType: "Aktie", sector: "Einzelhandelsriese", price: 74.80, dayChangePct: 0.50, isin: "US9311421039" },
  { name: "Costco Wholesale Corp.", ticker: "COST", assetType: "Aktie", sector: "Mitglieder-Großhandel", price: 885.00, dayChangePct: 0.85, isin: "US22160K1051" },
  { name: "Procter & Gamble Co.", ticker: "PG", assetType: "Aktie", sector: "Konsumgüter & Haushaltswaren", price: 168.20, dayChangePct: 0.20, isin: "US7427181091" },
  { name: "The Coca-Cola Company", ticker: "KO", assetType: "Aktie", sector: "Getränkekonzern", price: 68.40, dayChangePct: 0.15, isin: "US1912161007" },
  { name: "PepsiCo Inc.", ticker: "PEP", assetType: "Aktie", sector: "Getränke & Snacks", price: 174.60, dayChangePct: 0.30, isin: "US7134481081" },
  { name: "McDonald's Corporation", ticker: "MCD", assetType: "Aktie", sector: "Systemgastronomie & Franchising", price: 288.00, dayChangePct: 0.40, isin: "US5801351017" },
  { name: "Nike Inc. (Class B)", ticker: "NKE", assetType: "Aktie", sector: "Sportbekleidung & Schuhe", price: 82.50, dayChangePct: -0.40, isin: "US6541061031" },
  { name: "The Home Depot Inc.", ticker: "HD", assetType: "Aktie", sector: "Baumarktkette & Renovierung", price: 368.00, dayChangePct: 0.60, isin: "US4370761029" },
  { name: "Starbucks Corporation", ticker: "SBUX", assetType: "Aktie", sector: "Kaffeekette & Gastronomie", price: 92.40, dayChangePct: 1.80, isin: "US8552441094" },
  { name: "Target Corporation", ticker: "TGT", assetType: "Aktie", sector: "Einzelhandelskette", price: 154.00, dayChangePct: 0.45, isin: "US87612E1064" },
  { name: "The Walt Disney Company", ticker: "DIS", assetType: "Aktie", sector: "Medien, Freizeitparks & Streaming", price: 96.40, dayChangePct: -0.25, isin: "US2546871060" },
  { name: "Warner Bros. Discovery", ticker: "WBD", assetType: "Aktie", sector: "Medien & Entertainment", price: 7.80, dayChangePct: -1.20, isin: "US9344231041" },
  { name: "Spotify Technology S.A.", ticker: "SPOT", assetType: "Aktie", sector: "Audio- & Musik-Streaming", price: 342.10, dayChangePct: 1.10, isin: "LU1778762911" },
  { name: "Uber Technologies Inc.", ticker: "UBER", assetType: "Aktie", sector: "Fahrdienst, Lieferdienst & Logistik", price: 68.90, dayChangePct: 1.60, isin: "US90353T1007" },
  { name: "Airbnb Inc.", ticker: "ABNB", assetType: "Aktie", sector: "Reise- & Unterkunfts-Plattform", price: 116.30, dayChangePct: -0.90, isin: "US0090661010" },
  { name: "Booking Holdings Inc.", ticker: "BKNG", assetType: "Aktie", sector: "Online-Reisebuchungen (Booking/Kayak)", price: 3950.00, dayChangePct: 0.75, isin: "US09857L1089" },
  { name: "DoorDash Inc.", ticker: "DASH", assetType: "Aktie", sector: "Essenslieferung & On-Demand Delivery", price: 128.40, dayChangePct: 2.10, isin: "US25809K1051" },
  { name: "Alibaba Group Holding", ticker: "BABA", assetType: "Aktie", sector: "E-Commerce & Cloud China", price: 82.30, dayChangePct: 1.40, isin: "US01609W1027" },
  { name: "PDD Holdings (Temu / Pinduoduo)", ticker: "PDD", assetType: "Aktie", sector: "E-Commerce Plattform", price: 98.50, dayChangePct: 2.90, isin: "US7223041028" },
  { name: "MercadoLibre Inc.", ticker: "MELI", assetType: "Aktie", sector: "E-Commerce & Fintech Lateinamerika", price: 1980.00, dayChangePct: 1.80, isin: "US58733R1023" },
  { name: "Sony Group Corporation", ticker: "SONY", assetType: "Aktie", sector: "Gaming (PlayStation), Entertainment & Sensoren", price: 88.50, dayChangePct: 0.70, isin: "US8356993076" },

  // --- INDUSTRIE, RÜSTUNG, ENERGIE & ROHSTOFFE ---
  { name: "Lockheed Martin Corp.", ticker: "LMT", assetType: "Aktie", sector: "Rüstung & Kampfflugzeuge (F-35)", price: 548.00, dayChangePct: 1.20, isin: "US5398301094" },
  { name: "RTX Corporation (Raytheon)", ticker: "RTX", assetType: "Aktie", sector: "Luftfahrt & Flugabwehr (Patriot)", price: 118.50, dayChangePct: 0.95, isin: "US75513E1010" },
  { name: "The Boeing Company", ticker: "BA", assetType: "Aktie", sector: "Luftfahrt & Raumfahrt", price: 162.00, dayChangePct: -0.80, isin: "US0970231058" },
  { name: "General Electric (GE Aerospace)", ticker: "GE", assetType: "Aktie", sector: "Flugzeugtriebwerke & Luftfahrt", price: 178.40, dayChangePct: 1.10, isin: "US3696043013" },
  { name: "Caterpillar Inc.", ticker: "CAT", assetType: "Aktie", sector: "Baumaschinen & Bergbau-Equipment", price: 348.00, dayChangePct: 0.85, isin: "US1491231015" },
  { name: "Deere & Company (John Deere)", ticker: "DE", assetType: "Aktie", sector: "Landmaschinen & Smart Farming", price: 382.00, dayChangePct: 0.40, isin: "US2441991054" },
  { name: "Honeywell International", ticker: "HON", assetType: "Aktie", sector: "Industriekonglomerat & Luftfahrttechnik", price: 204.50, dayChangePct: 0.30, isin: "US4385161066" },
  { name: "3M Company", ticker: "MMM", assetType: "Aktie", sector: "Industrie- & Konsumgüter", price: 128.00, dayChangePct: 0.60, isin: "US88579Y1010" },
  { name: "Northrop Grumman Corp.", ticker: "NOC", assetType: "Aktie", sector: "Tarnkappenbomber & Rüstung (B-21)", price: 512.00, dayChangePct: 1.05, isin: "US6668071029" },
  { name: "General Dynamics Corp.", ticker: "GD", assetType: "Aktie", sector: "Panzer, U-Boote & Gulfstream", price: 298.00, dayChangePct: 0.70, isin: "US3695501086" },
  { name: "Exxon Mobil Corporation", ticker: "XOM", assetType: "Aktie", sector: "Öl- & Gaskonzern", price: 114.20, dayChangePct: 0.65, isin: "US30231G1022" },
  { name: "Chevron Corporation", ticker: "CVX", assetType: "Aktie", sector: "Integrierter Energiekonzern", price: 142.80, dayChangePct: 0.50, isin: "US1667641005" },
  { name: "ConocoPhillips", ticker: "COP", assetType: "Aktie", sector: "Öl- & Gasförderung", price: 106.40, dayChangePct: 0.80, isin: "US20825C1045" },
  { name: "Enphase Energy Inc.", ticker: "ENPH", assetType: "Aktie", sector: "Solar-Mikrowechselrichter & Batterien", price: 104.20, dayChangePct: 2.80, isin: "US29355A1079" },
  { name: "First Solar Inc.", ticker: "FSLR", assetType: "Aktie", sector: "Dünnschicht-Solarmodule", price: 228.00, dayChangePct: 3.20, isin: "US3364331070" },
  { name: "NextEra Energy Inc.", ticker: "NEE", assetType: "Aktie", sector: "Erneuerbare Energien & US-Versorger", price: 78.50, dayChangePct: 0.40, isin: "US65339F1012" },
  { name: "Southern Company", ticker: "SO", assetType: "Aktie", sector: "Energieversorger & Kernkraft", price: 86.40, dayChangePct: 0.20, isin: "US8425871071" },
  { name: "Freeport-McMoRan Inc.", ticker: "FCX", assetType: "Aktie", sector: "Kupfer- & Goldminen", price: 44.80, dayChangePct: 1.40, isin: "US35671D8570" },
  { name: "Albemarle Corporation", ticker: "ALB", assetType: "Aktie", sector: "Lithium-Förderung für E-Mobilität", price: 88.50, dayChangePct: 2.60, isin: "US0126531013" },
  { name: "Newmont Corporation", ticker: "NEM", assetType: "Aktie", sector: "Goldförderung", price: 48.20, dayChangePct: 1.10, isin: "US6516391066" },

  // --- POPULÄRE ETFS & INDEXFONDS ---
  { name: "iShares Core MSCI World ETF (Acc)", ticker: "EUNL", assetType: "ETF", sector: "Weltweite Aktien (Entwickelte Länder)", price: 94.20, dayChangePct: 0.35, isin: "IE00B4L5Y983" },
  { name: "Vanguard FTSE All-World ETF (Acc)", ticker: "VWCE", assetType: "ETF", sector: "Weltweite Aktien (All-Cap & EM)", price: 122.80, dayChangePct: 0.32, isin: "IE00BK5BQT36" },
  { name: "Vanguard FTSE All-World ETF (Dist)", ticker: "VWRL", assetType: "ETF", sector: "Weltweite Aktien (Ausschüttend)", price: 118.50, dayChangePct: 0.30, isin: "IE00B3RBWM25" },
  { name: "iShares Core S&P 500 UCITS ETF", ticker: "SXR8", assetType: "ETF", sector: "US Großunternehmen (500 größte Werte)", price: 540.60, dayChangePct: 0.48, isin: "IE00B5BMR087" },
  { name: "iShares NASDAQ 100 UCITS ETF", ticker: "SXRV", assetType: "ETF", sector: "US Technologie- & Wachstumsaktien", price: 980.40, dayChangePct: 0.92, isin: "IE00B53SZB19" },
  { name: "iShares Core MSCI Emerging Markets IMI", ticker: "IS3N", assetType: "ETF", sector: "Schwellenländer Aktien (EM)", price: 32.40, dayChangePct: 0.25, isin: "IE00BKM4GZ66" },
  { name: "Vanguard S&P 500 UCITS ETF (Dist)", ticker: "VUSA", assetType: "ETF", sector: "US Aktien (Ausschüttend)", price: 92.60, dayChangePct: 0.45, isin: "IE00B3XXRP09" },
  { name: "iShares STOXX Europe 600 UCITS ETF", ticker: "EXSA", assetType: "ETF", sector: "Europäische Aktien (600 Werte)", price: 52.80, dayChangePct: 0.30, isin: "DE0002635307" },
  { name: "Xtrackers DAX UCITS ETF", ticker: "DBXD", assetType: "ETF", sector: "Deutsche Leitaktien (DAX 40)", price: 174.50, dayChangePct: 0.40, isin: "LU0274211480" },
  { name: "iShares Global Clean Energy UCITS ETF", ticker: "INRG", assetType: "ETF", sector: "Erneuerbare Energien & Solar", price: 8.40, dayChangePct: 1.20, isin: "IE00B1XNHC34" },
  { name: "VanEck Semiconductor UCITS ETF", ticker: "SMH", assetType: "ETF", sector: "Globale Halbleiterunternehmen", price: 42.60, dayChangePct: 2.10, isin: "IE00BMC38736" },
  { name: "iShares MSCI India UCITS ETF", ticker: "NDIA", assetType: "ETF", sector: "Indischer Wachstumsmarkt", price: 8.80, dayChangePct: 0.70, isin: "IE00BZ485H72" },
  { name: "Xtrackers EUR Overnight Rate (Geldmarkt)", ticker: "DBX0AN", assetType: "ETF", sector: "EUR Geldmarkt (€STR Zins)", price: 141.25, dayChangePct: 0.01, isin: "LU0290358497" },
  { name: "iShares Core Euro Corporate Bond", ticker: "IEAC", assetType: "ETF", sector: "Europäische Unternehmensanleihen", price: 126.80, dayChangePct: 0.08, isin: "IE00B3F81R35" },
  { name: "Incomeshares Tesla Options ETP", ticker: "TSLY", assetType: "ETF", sector: "Options Income ETP", price: 11.20, dayChangePct: 0.45, isin: "US9219468858" },
  { name: "Leverage Shares 3x Long Tesla ETP", ticker: "TSL3", assetType: "Krypto", sector: "Hebel-ETP (3x Long)", price: 4.44, dayChangePct: 5.62, isin: "XS2297549128" },
  { name: "Leverage Shares -1x Short Tesla ETP", ticker: "TSLS", assetType: "Krypto", sector: "Short-ETP (-1x)", price: 8.12, dayChangePct: -1.82, isin: "XS2297551298" },
  { name: "Leverage Shares -3x Short Tesla ETP", ticker: "3STS", assetType: "Krypto", sector: "Short-ETP (-3x)", price: 2.10, dayChangePct: -5.40, isin: "XS2472334809" },

  // --- KRYPTOWÄHRUNGEN & DIGITALE ASSETS ---
  { name: "Bitcoin (BTC / EUR)", ticker: "BTC", assetType: "Krypto", sector: "Kryptowährung / Digitales Gold", price: 58400.00, dayChangePct: 2.85, isin: "BTC-EUR" },
  { name: "Ethereum (ETH / EUR)", ticker: "ETH", assetType: "Krypto", sector: "Smart Contract Plattform", price: 2650.00, dayChangePct: 3.40, isin: "ETH-EUR" },
  { name: "Solana (SOL / EUR)", ticker: "SOL", assetType: "Krypto", sector: "Hochleistungs-Blockchain", price: 145.20, dayChangePct: 5.10, isin: "SOL-EUR" },
  { name: "Ripple (XRP / EUR)", ticker: "XRP", assetType: "Krypto", sector: "Zahlungsnetzwerk", price: 0.58, dayChangePct: 1.40, isin: "XRP-EUR" },
  { name: "Cardano (ADA / EUR)", ticker: "ADA", assetType: "Krypto", sector: "Proof-of-Stake Blockchain", price: 0.35, dayChangePct: 2.10, isin: "ADA-EUR" },
  { name: "Avalanche (AVAX / EUR)", ticker: "AVAX", assetType: "Krypto", sector: "Dezentrale Finanzen / DeFi", price: 24.80, dayChangePct: 4.20, isin: "AVAX-EUR" },
  { name: "Chainlink (LINK / EUR)", ticker: "LINK", assetType: "Krypto", sector: "Dezentrales Oracle-Netzwerk", price: 11.20, dayChangePct: 3.80, isin: "LINK-EUR" },
  { name: "Polkadot (DOT / EUR)", ticker: "DOT", assetType: "Krypto", sector: "Multi-Chain Interoperabilität", price: 4.20, dayChangePct: 1.80, isin: "DOT-EUR" },
  { name: "Polygon (POL / EUR)", ticker: "POL", assetType: "Krypto", sector: "Ethereum Layer-2 Skalierung", price: 0.38, dayChangePct: 2.40, isin: "POL-EUR" },
  { name: "Uniswap (UNI / EUR)", ticker: "UNI", assetType: "Krypto", sector: "Dezentrale Krypto-Börse (DEX)", price: 6.90, dayChangePct: 3.10, isin: "UNI-EUR" },
  { name: "Dogecoin (DOGE / EUR)", ticker: "DOGE", assetType: "Krypto", sector: "Memecoin / Zahlungskrypto", price: 0.105, dayChangePct: 4.60, isin: "DOGE-EUR" }
];

  window.STOCK_CATALOG = catalog;
})();
